serviceAccount:
  create: true
  name: ${service_account_name}
  annotations:
    eks.amazonaws.com/role-arn: ${sa_role_arn}
mimir:
  structuredConfig:
    usage_stats:
      enabled: false
      installation_mode: helm
    
    blocks_storage:
      backend: s3
      s3:
        bucket_name: mimir-data-bucket
        endpoint: s3.us-east-1.amazonaws.com
        insecure: false
      tsdb:
        dir: /data/tsdb
    compactor:
      data_dir: /data
    multitenancy_enabled: false
    frontend:
      align_queries_with_step: true
      log_queries_longer_than: 10s
    ingester:
      instance_limits:
        max_ingestion_rate: 0
      ring:
        final_sleep: 0s
        num_tokens: 512
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    server:
      log_level: debug
      grpc_server_max_concurrent_streams: 1000
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
    limits:
      ingestion_rate: 80000
      max_global_series_per_metric: 0
      max_global_series_per_user: 0
      max_label_names_per_series: 40
    memberlist:
      abort_if_cluster_join_fails: false
      compression_enabled: false
    runtime_config:
      file: /var/{{ include "mimir.name" . }}/runtime.yaml
minio:
  enabled: false
querier:
  replicas: 2
alertmanager:
  enabled: false
ruler:
  enabled: false
ingester:
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    enabled: true
    annotations: {}
    accessModes:
      - ReadWriteOnce
    size: 5Gi
store_gateway:
 zoneAwareReplication:
  enabled: false
nginx:
 ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      acme.cert-manager.io/http01-edit-in-place: "true"
      external-dns.alpha.kubernetes.io/hostname: ${domain_name}
    hosts:
      - host: ${domain_name}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - ${domain_name}
        secretName: mimir-tls